### ISSUE TITLE
T2B_ALIAS_UNKNOWN_ERROR

### ISSUE THREAD

**Issue by mbajur** [maubot/gitlab#12]
I'm not sure if that's a proper place to adk for support but if not, please forgive me and close the issue.

1. I have invited bot to my channel (#prismo:matrix.org)
2. I have created a webhook for my gitlab project and pointed it to `https://t2bot.io/gitlab/webhooks?room=!IadFDmzRTSlgzQTZHj:matrix.org` (that's the original ID of my channel)

When trying to send a test event through gitlab UI, gitlab gives me:

```
Hook executed successfully but returned HTTP 404 {"statusCode"=>404, "success"=>false, "error"=>"<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\">\n<title>Error</title>\n</head>\n<body>\n<pre>Cannot POST /gitlab/webhooks</pre>\n</body>\n</html>\n", "errcode"=>"T2B_ALIAS_UNKNOWN_ERROR"}
```

Is there anything obvious i've done wrong in here? Thanks in advance!

**Comment by mbajur** [comment]
It seems that it's just the issue with the gitlab webhook "Test" feature as bot works fine and sends notifications to my channel.

Anyway, that's probably still a bug on gitlab bot side.

**Comment by turt2live** [comment]
I just came back around to this. It appears as though it was a configuration error on my end (hence the error code being from a completely different bot). If the issue persists, please come by [#help:t2bot.io](https://matrix.to/#/#help:t2bot.io) to let me know.
