### ISSUE TITLE
Add usage instructions to readme

### ISSUE THREAD

**Issue by turt2live** [maubot/gitlab#2]
It's possible to figure this out the hard way, but having it in the readme would be infinitely more helpful :)

**Comment by kaystrobach** [comment]
@urt2live, can you please create a PR which sums up your findings.

**Comment by mozzieongit** [comment]
Hi, 
here an addition to the readme from the matrix room #maubot:maunium.net if other people like me, who don't fully read the config files:
The webhooks path to point to:
https://<server_name>/<plugin_base_path_from_maubot_config_yaml>/<instance_id>/webhooks?room=<room_id>
ex: https://maubot.example.org/_matrix/maubot/plugin/gitlab-instance/webhooks?room=!<room_id>

Thanks @tulir
