### ISSUE TITLE
Add support for configuring webhooks with commands

### ISSUE THREAD

**Issue by tulir** [maubot/gitlab#28]
Instead of requiring the user manually create the webhook, the bot should have an option to do it automatically. This will also make it possible to fix the webhook secret being public.

* [ ] Add command to create, configure and delete room notification webhooks
* [ ] Store per-room+webhook secrets in the db and check against those instead of the global secret

**Comment by nanonyme** [comment]
Please consider prioritizing this. Also access control so that only moderators and admins can manage the webhooks to windows of abuse.

**Comment by tulir** [comment]
`!gitlab webhook add` is now a thing which creates a webhook with a random secret that only works for that specific room. Split out permissions and deleting into #46 and #47
