### ISSUE TITLE
Bad English message "approveded" in Merge request events

### ISSUE THREAD

**Issue by cmuller** [maubot/gitlab#37]
Hello,

When selecting "Merge request events" in the Gitlab webhooks list, maubot gitlab is not formatting the right message. It tries to make a _doubled_ past tense of "approved" and so we can see a message like:

[group / repo] User **approveded** merge request "description..."

This is due to the `past_tense` function in `gitlab_matrix/gitlab_hook.py`.

**Comment by nanonyme** [comment]
I suppose this still isn't deployed as the error is still present?

**Comment by tulir** [comment]
This is not a service, deploying updates is up to the admins of whatever instance you're using.

**Comment by nanonyme** [comment]
I see, thank you.
