### ISSUE TITLE
OptRepoArgument does not match all possible repository names

### ISSUE THREAD

**Issue by mkdryden** [maubot/gitlab#50]
It seems that OptRepoArgument uses \w in its regex expression to match repository names, which means that repositories with - in their name (which are pretty common) do not work in commands that call for a repository argument. See:

https://github.com/maubot/gitlab/blob/e18db369c603b2dff2807507c3c7aaea5b78057a/gitlab_matrix/util/arguments.py#L53

**Comment by hexxone** [comment]
Seems like this was fixxed, why is it not closed?

**Comment by mkdryden** [comment]
Indeed, it seems to have been fixed in https://github.com/maubot/gitlab/commit/58bdca13a14044884f41a1d2b5d4480397a8d885.
