### ISSUE TITLE
Allow different access_token logins based on project

### ISSUE THREAD

**Issue by smoebody** [maubot/gitlab#60]
Hi,

first of all thanks for the maubot, especially the gitlab-plugin.

Now i am setting up multiple rooms where the bot shall keep the members updated about a different project. Therefore i tried to login to the gitlab-server multiple times (from each room with the [projects access_token] only to find out that i can login to a server only once.
> sqlite3.IntegrityError: UNIQUE constraint failed: token.user_id, token.gitlab_server

To allow one bot to manage multiple projects on one server it is necessary to give the bot an access_token created for a user who is able to access all these projects. This is suboptimal in my opinion.
Instead i wish for the ability to link a room to a specific access_token (if specified). Also in order to keep members in other rooms from messing up projects they don't belong to.

I am not familar with python, although I can offer to test.

cheers,
smoe

[projects access_token]: https://docs.gitlab.com/ee/user/project/settings/project_access_tokens.html

**Comment by tulir** [comment]
Logging in is per-user, not per-room

**Comment by smoebody** [comment]
I know.
I suggest to change that.

**Comment by tulir** [comment]
Room-wide logins sound dangerous and not particularly useful. Each user can log in with their own token.

**Comment by smoebody** [comment]
Im afraid i do not understand.
You mean, when i invite the bot to a room and login to a gitlab server, only I are able to run `!gitlab`-commands?

**Comment by tulir** [comment]
Yes, that's what I mean by login being per-user. After you login in a private chat with the bot, you can use the bot commands in any room. Nobody else can use commands unless they log in with their own tokens.

**Comment by smoebody** [comment]
Ah, ok. Thanks for the enlightment. Then it all makes sense of course. 

But the messages the Bot posts in a room are visible to all members?

**Comment by tulir** [comment]
Yes, webhook messages are visible to everyone. They can also be set up manually without logging in (from the gitlab web interface)

**Comment by smoebody** [comment]
All right. Thanks. Closing.
