### ISSUE TITLE
not enough arguments in call to git.Commits.GetCommitDiff

### ISSUE THREAD

**Issue by theodotos** [maubot/gitlab#7]
Hi, Trying to build maulabbot and getting this:

```
$ go get github.com/tulir/maulabbot
# github.com/tulir/maulabbot
../../go/src/github.com/tulir/maulabbot/commands.go:160:44: not enough arguments in call to git.Commits.GetCommitDiff
	have (string, string)
	want (interface {}, string, *"github.com/xanzy/go-gitlab".GetCommitDiffOptions, ..."github.com/xanzy/go-gitlab".OptionFunc)
../../go/src/github.com/tulir/maulabbot/commands.go:311:14: unknown field 'ListOptions' in struct literal of type "github.com/xanzy/go-gitlab".ListIssueNotesOptions
```

I am a complete go illiterate so I may be missing something pretty obvious here.

**Comment by tulir** [comment]
I haven't updated the bot in a while and didn't use any dependency version locking, so it's broken on the latest version. I'm planning on migrating this to use [maubot](https://github.com/maubot/maubot) soon, so I'll at least fix the worst problems then.
